org: stefanlearning
service: shui-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  httpApi:
    cors: true
  iam:
    role: arn:aws:iam::643575569582:role/BasicLambdaRole

functions:
  # ----- Auth -----
  LoginUser:
    handler: functions/auth/LoginUser/index.handler
    events:
      - httpApi:
        path: /api/auth/login
        method: POST

resources:
  Resources:
    ShiaTable:
      Type: AWS::DynamoDB::ShiaTable
      Properties:
        TableName: shia-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
